################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow/tensorflow/lite/micro/kernels/activations.cc \
../tensorflow/tensorflow/lite/micro/kernels/activations_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/add.cc \
../tensorflow/tensorflow/lite/micro/kernels/add_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/add_n.cc \
../tensorflow/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tensorflow/tensorflow/lite/micro/kernels/assign_variable.cc \
../tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tensorflow/tensorflow/lite/micro/kernels/broadcast_args.cc \
../tensorflow/tensorflow/lite/micro/kernels/broadcast_to.cc \
../tensorflow/tensorflow/lite/micro/kernels/call_once.cc \
../tensorflow/tensorflow/lite/micro/kernels/cast.cc \
../tensorflow/tensorflow/lite/micro/kernels/ceil.cc \
../tensorflow/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/comparisons.cc \
../tensorflow/tensorflow/lite/micro/kernels/concatenation.cc \
../tensorflow/tensorflow/lite/micro/kernels/conv.cc \
../tensorflow/tensorflow/lite/micro/kernels/conv_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/cumsum.cc \
../tensorflow/tensorflow/lite/micro/kernels/depth_to_space.cc \
../tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/dequantize.cc \
../tensorflow/tensorflow/lite/micro/kernels/dequantize_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tensorflow/tensorflow/lite/micro/kernels/div.cc \
../tensorflow/tensorflow/lite/micro/kernels/elementwise.cc \
../tensorflow/tensorflow/lite/micro/kernels/elu.cc \
../tensorflow/tensorflow/lite/micro/kernels/ethosu.cc \
../tensorflow/tensorflow/lite/micro/kernels/exp.cc \
../tensorflow/tensorflow/lite/micro/kernels/expand_dims.cc \
../tensorflow/tensorflow/lite/micro/kernels/fill.cc \
../tensorflow/tensorflow/lite/micro/kernels/floor.cc \
../tensorflow/tensorflow/lite/micro/kernels/floor_div.cc \
../tensorflow/tensorflow/lite/micro/kernels/floor_mod.cc \
../tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc \
../tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/gather.cc \
../tensorflow/tensorflow/lite/micro/kernels/gather_nd.cc \
../tensorflow/tensorflow/lite/micro/kernels/hard_swish.cc \
../tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/if.cc \
../tensorflow/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tensorflow/tensorflow/lite/micro/kernels/kernel_util.cc \
../tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tensorflow/tensorflow/lite/micro/kernels/l2norm.cc \
../tensorflow/tensorflow/lite/micro/kernels/leaky_relu.cc \
../tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/log_softmax.cc \
../tensorflow/tensorflow/lite/micro/kernels/logical.cc \
../tensorflow/tensorflow/lite/micro/kernels/logical_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/logistic.cc \
../tensorflow/tensorflow/lite/micro/kernels/logistic_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/lstm_eval.cc \
../tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tensorflow/tensorflow/lite/micro/kernels/mirror_pad.cc \
../tensorflow/tensorflow/lite/micro/kernels/mul.cc \
../tensorflow/tensorflow/lite/micro/kernels/mul_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/neg.cc \
../tensorflow/tensorflow/lite/micro/kernels/pack.cc \
../tensorflow/tensorflow/lite/micro/kernels/pad.cc \
../tensorflow/tensorflow/lite/micro/kernels/pooling.cc \
../tensorflow/tensorflow/lite/micro/kernels/pooling_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/prelu.cc \
../tensorflow/tensorflow/lite/micro/kernels/prelu_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/quantize.cc \
../tensorflow/tensorflow/lite/micro/kernels/quantize_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/read_variable.cc \
../tensorflow/tensorflow/lite/micro/kernels/reduce.cc \
../tensorflow/tensorflow/lite/micro/kernels/reduce_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/reshape.cc \
../tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tensorflow/tensorflow/lite/micro/kernels/round.cc \
../tensorflow/tensorflow/lite/micro/kernels/select.cc \
../tensorflow/tensorflow/lite/micro/kernels/shape.cc \
../tensorflow/tensorflow/lite/micro/kernels/slice.cc \
../tensorflow/tensorflow/lite/micro/kernels/softmax.cc \
../tensorflow/tensorflow/lite/micro/kernels/softmax_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tensorflow/tensorflow/lite/micro/kernels/space_to_depth.cc \
../tensorflow/tensorflow/lite/micro/kernels/split.cc \
../tensorflow/tensorflow/lite/micro/kernels/split_v.cc \
../tensorflow/tensorflow/lite/micro/kernels/squared_difference.cc \
../tensorflow/tensorflow/lite/micro/kernels/squeeze.cc \
../tensorflow/tensorflow/lite/micro/kernels/strided_slice.cc \
../tensorflow/tensorflow/lite/micro/kernels/sub.cc \
../tensorflow/tensorflow/lite/micro/kernels/sub_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/svdf.cc \
../tensorflow/tensorflow/lite/micro/kernels/svdf_common.cc \
../tensorflow/tensorflow/lite/micro/kernels/tanh.cc \
../tensorflow/tensorflow/lite/micro/kernels/transpose.cc \
../tensorflow/tensorflow/lite/micro/kernels/transpose_conv.cc \
../tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../tensorflow/tensorflow/lite/micro/kernels/unpack.cc \
../tensorflow/tensorflow/lite/micro/kernels/var_handle.cc \
../tensorflow/tensorflow/lite/micro/kernels/while.cc \
../tensorflow/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tensorflow/tensorflow/lite/micro/kernels/activations.d \
./tensorflow/tensorflow/lite/micro/kernels/activations_common.d \
./tensorflow/tensorflow/lite/micro/kernels/add.d \
./tensorflow/tensorflow/lite/micro/kernels/add_common.d \
./tensorflow/tensorflow/lite/micro/kernels/add_n.d \
./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.d \
./tensorflow/tensorflow/lite/micro/kernels/assign_variable.d \
./tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tensorflow/tensorflow/lite/micro/kernels/broadcast_args.d \
./tensorflow/tensorflow/lite/micro/kernels/broadcast_to.d \
./tensorflow/tensorflow/lite/micro/kernels/call_once.d \
./tensorflow/tensorflow/lite/micro/kernels/cast.d \
./tensorflow/tensorflow/lite/micro/kernels/ceil.d \
./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.d \
./tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tensorflow/tensorflow/lite/micro/kernels/comparisons.d \
./tensorflow/tensorflow/lite/micro/kernels/concatenation.d \
./tensorflow/tensorflow/lite/micro/kernels/conv.d \
./tensorflow/tensorflow/lite/micro/kernels/conv_common.d \
./tensorflow/tensorflow/lite/micro/kernels/cumsum.d \
./tensorflow/tensorflow/lite/micro/kernels/depth_to_space.d \
./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.d \
./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tensorflow/tensorflow/lite/micro/kernels/dequantize.d \
./tensorflow/tensorflow/lite/micro/kernels/dequantize_common.d \
./tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tensorflow/tensorflow/lite/micro/kernels/div.d \
./tensorflow/tensorflow/lite/micro/kernels/elementwise.d \
./tensorflow/tensorflow/lite/micro/kernels/elu.d \
./tensorflow/tensorflow/lite/micro/kernels/ethosu.d \
./tensorflow/tensorflow/lite/micro/kernels/exp.d \
./tensorflow/tensorflow/lite/micro/kernels/expand_dims.d \
./tensorflow/tensorflow/lite/micro/kernels/fill.d \
./tensorflow/tensorflow/lite/micro/kernels/floor.d \
./tensorflow/tensorflow/lite/micro/kernels/floor_div.d \
./tensorflow/tensorflow/lite/micro/kernels/floor_mod.d \
./tensorflow/tensorflow/lite/micro/kernels/fully_connected.d \
./tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tensorflow/tensorflow/lite/micro/kernels/gather.d \
./tensorflow/tensorflow/lite/micro/kernels/gather_nd.d \
./tensorflow/tensorflow/lite/micro/kernels/hard_swish.d \
./tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.d \
./tensorflow/tensorflow/lite/micro/kernels/if.d \
./tensorflow/tensorflow/lite/micro/kernels/kernel_runner.d \
./tensorflow/tensorflow/lite/micro/kernels/kernel_util.d \
./tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tensorflow/tensorflow/lite/micro/kernels/l2norm.d \
./tensorflow/tensorflow/lite/micro/kernels/leaky_relu.d \
./tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tensorflow/tensorflow/lite/micro/kernels/log_softmax.d \
./tensorflow/tensorflow/lite/micro/kernels/logical.d \
./tensorflow/tensorflow/lite/micro/kernels/logical_common.d \
./tensorflow/tensorflow/lite/micro/kernels/logistic.d \
./tensorflow/tensorflow/lite/micro/kernels/logistic_common.d \
./tensorflow/tensorflow/lite/micro/kernels/lstm_eval.d \
./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.d \
./tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tensorflow/tensorflow/lite/micro/kernels/mirror_pad.d \
./tensorflow/tensorflow/lite/micro/kernels/mul.d \
./tensorflow/tensorflow/lite/micro/kernels/mul_common.d \
./tensorflow/tensorflow/lite/micro/kernels/neg.d \
./tensorflow/tensorflow/lite/micro/kernels/pack.d \
./tensorflow/tensorflow/lite/micro/kernels/pad.d \
./tensorflow/tensorflow/lite/micro/kernels/pooling.d \
./tensorflow/tensorflow/lite/micro/kernels/pooling_common.d \
./tensorflow/tensorflow/lite/micro/kernels/prelu.d \
./tensorflow/tensorflow/lite/micro/kernels/prelu_common.d \
./tensorflow/tensorflow/lite/micro/kernels/quantize.d \
./tensorflow/tensorflow/lite/micro/kernels/quantize_common.d \
./tensorflow/tensorflow/lite/micro/kernels/read_variable.d \
./tensorflow/tensorflow/lite/micro/kernels/reduce.d \
./tensorflow/tensorflow/lite/micro/kernels/reduce_common.d \
./tensorflow/tensorflow/lite/micro/kernels/reshape.d \
./tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.d \
./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tensorflow/tensorflow/lite/micro/kernels/round.d \
./tensorflow/tensorflow/lite/micro/kernels/select.d \
./tensorflow/tensorflow/lite/micro/kernels/shape.d \
./tensorflow/tensorflow/lite/micro/kernels/slice.d \
./tensorflow/tensorflow/lite/micro/kernels/softmax.d \
./tensorflow/tensorflow/lite/micro/kernels/softmax_common.d \
./tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tensorflow/tensorflow/lite/micro/kernels/space_to_depth.d \
./tensorflow/tensorflow/lite/micro/kernels/split.d \
./tensorflow/tensorflow/lite/micro/kernels/split_v.d \
./tensorflow/tensorflow/lite/micro/kernels/squared_difference.d \
./tensorflow/tensorflow/lite/micro/kernels/squeeze.d \
./tensorflow/tensorflow/lite/micro/kernels/strided_slice.d \
./tensorflow/tensorflow/lite/micro/kernels/sub.d \
./tensorflow/tensorflow/lite/micro/kernels/sub_common.d \
./tensorflow/tensorflow/lite/micro/kernels/svdf.d \
./tensorflow/tensorflow/lite/micro/kernels/svdf_common.d \
./tensorflow/tensorflow/lite/micro/kernels/tanh.d \
./tensorflow/tensorflow/lite/micro/kernels/transpose.d \
./tensorflow/tensorflow/lite/micro/kernels/transpose_conv.d \
./tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./tensorflow/tensorflow/lite/micro/kernels/unpack.d \
./tensorflow/tensorflow/lite/micro/kernels/var_handle.d \
./tensorflow/tensorflow/lite/micro/kernels/while.d \
./tensorflow/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tensorflow/tensorflow/lite/micro/kernels/activations.o \
./tensorflow/tensorflow/lite/micro/kernels/activations_common.o \
./tensorflow/tensorflow/lite/micro/kernels/add.o \
./tensorflow/tensorflow/lite/micro/kernels/add_common.o \
./tensorflow/tensorflow/lite/micro/kernels/add_n.o \
./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.o \
./tensorflow/tensorflow/lite/micro/kernels/assign_variable.o \
./tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tensorflow/tensorflow/lite/micro/kernels/broadcast_args.o \
./tensorflow/tensorflow/lite/micro/kernels/broadcast_to.o \
./tensorflow/tensorflow/lite/micro/kernels/call_once.o \
./tensorflow/tensorflow/lite/micro/kernels/cast.o \
./tensorflow/tensorflow/lite/micro/kernels/ceil.o \
./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.o \
./tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tensorflow/tensorflow/lite/micro/kernels/comparisons.o \
./tensorflow/tensorflow/lite/micro/kernels/concatenation.o \
./tensorflow/tensorflow/lite/micro/kernels/conv.o \
./tensorflow/tensorflow/lite/micro/kernels/conv_common.o \
./tensorflow/tensorflow/lite/micro/kernels/cumsum.o \
./tensorflow/tensorflow/lite/micro/kernels/depth_to_space.o \
./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.o \
./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tensorflow/tensorflow/lite/micro/kernels/dequantize.o \
./tensorflow/tensorflow/lite/micro/kernels/dequantize_common.o \
./tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tensorflow/tensorflow/lite/micro/kernels/div.o \
./tensorflow/tensorflow/lite/micro/kernels/elementwise.o \
./tensorflow/tensorflow/lite/micro/kernels/elu.o \
./tensorflow/tensorflow/lite/micro/kernels/ethosu.o \
./tensorflow/tensorflow/lite/micro/kernels/exp.o \
./tensorflow/tensorflow/lite/micro/kernels/expand_dims.o \
./tensorflow/tensorflow/lite/micro/kernels/fill.o \
./tensorflow/tensorflow/lite/micro/kernels/floor.o \
./tensorflow/tensorflow/lite/micro/kernels/floor_div.o \
./tensorflow/tensorflow/lite/micro/kernels/floor_mod.o \
./tensorflow/tensorflow/lite/micro/kernels/fully_connected.o \
./tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tensorflow/tensorflow/lite/micro/kernels/gather.o \
./tensorflow/tensorflow/lite/micro/kernels/gather_nd.o \
./tensorflow/tensorflow/lite/micro/kernels/hard_swish.o \
./tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.o \
./tensorflow/tensorflow/lite/micro/kernels/if.o \
./tensorflow/tensorflow/lite/micro/kernels/kernel_runner.o \
./tensorflow/tensorflow/lite/micro/kernels/kernel_util.o \
./tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tensorflow/tensorflow/lite/micro/kernels/l2norm.o \
./tensorflow/tensorflow/lite/micro/kernels/leaky_relu.o \
./tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tensorflow/tensorflow/lite/micro/kernels/log_softmax.o \
./tensorflow/tensorflow/lite/micro/kernels/logical.o \
./tensorflow/tensorflow/lite/micro/kernels/logical_common.o \
./tensorflow/tensorflow/lite/micro/kernels/logistic.o \
./tensorflow/tensorflow/lite/micro/kernels/logistic_common.o \
./tensorflow/tensorflow/lite/micro/kernels/lstm_eval.o \
./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.o \
./tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tensorflow/tensorflow/lite/micro/kernels/mirror_pad.o \
./tensorflow/tensorflow/lite/micro/kernels/mul.o \
./tensorflow/tensorflow/lite/micro/kernels/mul_common.o \
./tensorflow/tensorflow/lite/micro/kernels/neg.o \
./tensorflow/tensorflow/lite/micro/kernels/pack.o \
./tensorflow/tensorflow/lite/micro/kernels/pad.o \
./tensorflow/tensorflow/lite/micro/kernels/pooling.o \
./tensorflow/tensorflow/lite/micro/kernels/pooling_common.o \
./tensorflow/tensorflow/lite/micro/kernels/prelu.o \
./tensorflow/tensorflow/lite/micro/kernels/prelu_common.o \
./tensorflow/tensorflow/lite/micro/kernels/quantize.o \
./tensorflow/tensorflow/lite/micro/kernels/quantize_common.o \
./tensorflow/tensorflow/lite/micro/kernels/read_variable.o \
./tensorflow/tensorflow/lite/micro/kernels/reduce.o \
./tensorflow/tensorflow/lite/micro/kernels/reduce_common.o \
./tensorflow/tensorflow/lite/micro/kernels/reshape.o \
./tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.o \
./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tensorflow/tensorflow/lite/micro/kernels/round.o \
./tensorflow/tensorflow/lite/micro/kernels/select.o \
./tensorflow/tensorflow/lite/micro/kernels/shape.o \
./tensorflow/tensorflow/lite/micro/kernels/slice.o \
./tensorflow/tensorflow/lite/micro/kernels/softmax.o \
./tensorflow/tensorflow/lite/micro/kernels/softmax_common.o \
./tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tensorflow/tensorflow/lite/micro/kernels/space_to_depth.o \
./tensorflow/tensorflow/lite/micro/kernels/split.o \
./tensorflow/tensorflow/lite/micro/kernels/split_v.o \
./tensorflow/tensorflow/lite/micro/kernels/squared_difference.o \
./tensorflow/tensorflow/lite/micro/kernels/squeeze.o \
./tensorflow/tensorflow/lite/micro/kernels/strided_slice.o \
./tensorflow/tensorflow/lite/micro/kernels/sub.o \
./tensorflow/tensorflow/lite/micro/kernels/sub_common.o \
./tensorflow/tensorflow/lite/micro/kernels/svdf.o \
./tensorflow/tensorflow/lite/micro/kernels/svdf_common.o \
./tensorflow/tensorflow/lite/micro/kernels/tanh.o \
./tensorflow/tensorflow/lite/micro/kernels/transpose.o \
./tensorflow/tensorflow/lite/micro/kernels/transpose_conv.o \
./tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./tensorflow/tensorflow/lite/micro/kernels/unpack.o \
./tensorflow/tensorflow/lite/micro/kernels/var_handle.o \
./tensorflow/tensorflow/lite/micro/kernels/while.o \
./tensorflow/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow/tensorflow/lite/micro/kernels/%.o tensorflow/tensorflow/lite/micro/kernels/%.su: ../tensorflow/tensorflow/lite/micro/kernels/%.cc tensorflow/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -D__FPU_PRESENT=1 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Drivers/CMSIS/Include -I../tensorflow -I../third_party/flatbuffers/include -I../third_party/gemmlowp -I../third_party/ruy -I../third_party/kissfft -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./tensorflow/tensorflow/lite/micro/kernels/activations.d ./tensorflow/tensorflow/lite/micro/kernels/activations.o ./tensorflow/tensorflow/lite/micro/kernels/activations.su ./tensorflow/tensorflow/lite/micro/kernels/activations_common.d ./tensorflow/tensorflow/lite/micro/kernels/activations_common.o ./tensorflow/tensorflow/lite/micro/kernels/activations_common.su ./tensorflow/tensorflow/lite/micro/kernels/add.d ./tensorflow/tensorflow/lite/micro/kernels/add.o ./tensorflow/tensorflow/lite/micro/kernels/add.su ./tensorflow/tensorflow/lite/micro/kernels/add_common.d ./tensorflow/tensorflow/lite/micro/kernels/add_common.o ./tensorflow/tensorflow/lite/micro/kernels/add_common.su ./tensorflow/tensorflow/lite/micro/kernels/add_n.d ./tensorflow/tensorflow/lite/micro/kernels/add_n.o ./tensorflow/tensorflow/lite/micro/kernels/add_n.su ./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.d ./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.o ./tensorflow/tensorflow/lite/micro/kernels/arg_min_max.su ./tensorflow/tensorflow/lite/micro/kernels/assign_variable.d ./tensorflow/tensorflow/lite/micro/kernels/assign_variable.o ./tensorflow/tensorflow/lite/micro/kernels/assign_variable.su ./tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./tensorflow/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./tensorflow/tensorflow/lite/micro/kernels/broadcast_args.d ./tensorflow/tensorflow/lite/micro/kernels/broadcast_args.o ./tensorflow/tensorflow/lite/micro/kernels/broadcast_args.su ./tensorflow/tensorflow/lite/micro/kernels/broadcast_to.d ./tensorflow/tensorflow/lite/micro/kernels/broadcast_to.o ./tensorflow/tensorflow/lite/micro/kernels/broadcast_to.su ./tensorflow/tensorflow/lite/micro/kernels/call_once.d ./tensorflow/tensorflow/lite/micro/kernels/call_once.o ./tensorflow/tensorflow/lite/micro/kernels/call_once.su ./tensorflow/tensorflow/lite/micro/kernels/cast.d ./tensorflow/tensorflow/lite/micro/kernels/cast.o ./tensorflow/tensorflow/lite/micro/kernels/cast.su ./tensorflow/tensorflow/lite/micro/kernels/ceil.d ./tensorflow/tensorflow/lite/micro/kernels/ceil.o ./tensorflow/tensorflow/lite/micro/kernels/ceil.su ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.d ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.o ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer.su ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.d ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.o ./tensorflow/tensorflow/lite/micro/kernels/circular_buffer_common.su ./tensorflow/tensorflow/lite/micro/kernels/comparisons.d ./tensorflow/tensorflow/lite/micro/kernels/comparisons.o ./tensorflow/tensorflow/lite/micro/kernels/comparisons.su ./tensorflow/tensorflow/lite/micro/kernels/concatenation.d ./tensorflow/tensorflow/lite/micro/kernels/concatenation.o ./tensorflow/tensorflow/lite/micro/kernels/concatenation.su ./tensorflow/tensorflow/lite/micro/kernels/conv.d ./tensorflow/tensorflow/lite/micro/kernels/conv.o ./tensorflow/tensorflow/lite/micro/kernels/conv.su ./tensorflow/tensorflow/lite/micro/kernels/conv_common.d ./tensorflow/tensorflow/lite/micro/kernels/conv_common.o ./tensorflow/tensorflow/lite/micro/kernels/conv_common.su ./tensorflow/tensorflow/lite/micro/kernels/cumsum.d ./tensorflow/tensorflow/lite/micro/kernels/cumsum.o ./tensorflow/tensorflow/lite/micro/kernels/cumsum.su ./tensorflow/tensorflow/lite/micro/kernels/depth_to_space.d ./tensorflow/tensorflow/lite/micro/kernels/depth_to_space.o ./tensorflow/tensorflow/lite/micro/kernels/depth_to_space.su ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.d ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.o ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv.su ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./tensorflow/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./tensorflow/tensorflow/lite/micro/kernels/dequantize.d ./tensorflow/tensorflow/lite/micro/kernels/dequantize.o ./tensorflow/tensorflow/lite/micro/kernels/dequantize.su ./tensorflow/tensorflow/lite/micro/kernels/dequantize_common.d ./tensorflow/tensorflow/lite/micro/kernels/dequantize_common.o ./tensorflow/tensorflow/lite/micro/kernels/dequantize_common.su ./tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.d ./tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.o ./tensorflow/tensorflow/lite/micro/kernels/detection_postprocess.su ./tensorflow/tensorflow/lite/micro/kernels/div.d ./tensorflow/tensorflow/lite/micro/kernels/div.o ./tensorflow/tensorflow/lite/micro/kernels/div.su ./tensorflow/tensorflow/lite/micro/kernels/elementwise.d ./tensorflow/tensorflow/lite/micro/kernels/elementwise.o ./tensorflow/tensorflow/lite/micro/kernels/elementwise.su ./tensorflow/tensorflow/lite/micro/kernels/elu.d ./tensorflow/tensorflow/lite/micro/kernels/elu.o ./tensorflow/tensorflow/lite/micro/kernels/elu.su ./tensorflow/tensorflow/lite/micro/kernels/ethosu.d ./tensorflow/tensorflow/lite/micro/kernels/ethosu.o ./tensorflow/tensorflow/lite/micro/kernels/ethosu.su ./tensorflow/tensorflow/lite/micro/kernels/exp.d ./tensorflow/tensorflow/lite/micro/kernels/exp.o ./tensorflow/tensorflow/lite/micro/kernels/exp.su ./tensorflow/tensorflow/lite/micro/kernels/expand_dims.d ./tensorflow/tensorflow/lite/micro/kernels/expand_dims.o ./tensorflow/tensorflow/lite/micro/kernels/expand_dims.su ./tensorflow/tensorflow/lite/micro/kernels/fill.d ./tensorflow/tensorflow/lite/micro/kernels/fill.o ./tensorflow/tensorflow/lite/micro/kernels/fill.su ./tensorflow/tensorflow/lite/micro/kernels/floor.d ./tensorflow/tensorflow/lite/micro/kernels/floor.o ./tensorflow/tensorflow/lite/micro/kernels/floor.su ./tensorflow/tensorflow/lite/micro/kernels/floor_div.d ./tensorflow/tensorflow/lite/micro/kernels/floor_div.o ./tensorflow/tensorflow/lite/micro/kernels/floor_div.su
	-$(RM) ./tensorflow/tensorflow/lite/micro/kernels/floor_mod.d ./tensorflow/tensorflow/lite/micro/kernels/floor_mod.o ./tensorflow/tensorflow/lite/micro/kernels/floor_mod.su ./tensorflow/tensorflow/lite/micro/kernels/fully_connected.d ./tensorflow/tensorflow/lite/micro/kernels/fully_connected.o ./tensorflow/tensorflow/lite/micro/kernels/fully_connected.su ./tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.d ./tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.o ./tensorflow/tensorflow/lite/micro/kernels/fully_connected_common.su ./tensorflow/tensorflow/lite/micro/kernels/gather.d ./tensorflow/tensorflow/lite/micro/kernels/gather.o ./tensorflow/tensorflow/lite/micro/kernels/gather.su ./tensorflow/tensorflow/lite/micro/kernels/gather_nd.d ./tensorflow/tensorflow/lite/micro/kernels/gather_nd.o ./tensorflow/tensorflow/lite/micro/kernels/gather_nd.su ./tensorflow/tensorflow/lite/micro/kernels/hard_swish.d ./tensorflow/tensorflow/lite/micro/kernels/hard_swish.o ./tensorflow/tensorflow/lite/micro/kernels/hard_swish.su ./tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.d ./tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.o ./tensorflow/tensorflow/lite/micro/kernels/hard_swish_common.su ./tensorflow/tensorflow/lite/micro/kernels/if.d ./tensorflow/tensorflow/lite/micro/kernels/if.o ./tensorflow/tensorflow/lite/micro/kernels/if.su ./tensorflow/tensorflow/lite/micro/kernels/kernel_runner.d ./tensorflow/tensorflow/lite/micro/kernels/kernel_runner.o ./tensorflow/tensorflow/lite/micro/kernels/kernel_runner.su ./tensorflow/tensorflow/lite/micro/kernels/kernel_util.d ./tensorflow/tensorflow/lite/micro/kernels/kernel_util.o ./tensorflow/tensorflow/lite/micro/kernels/kernel_util.su ./tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.d ./tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.o ./tensorflow/tensorflow/lite/micro/kernels/l2_pool_2d.su ./tensorflow/tensorflow/lite/micro/kernels/l2norm.d ./tensorflow/tensorflow/lite/micro/kernels/l2norm.o ./tensorflow/tensorflow/lite/micro/kernels/l2norm.su ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu.d ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu.o ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu.su ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.d ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.o ./tensorflow/tensorflow/lite/micro/kernels/leaky_relu_common.su ./tensorflow/tensorflow/lite/micro/kernels/log_softmax.d ./tensorflow/tensorflow/lite/micro/kernels/log_softmax.o ./tensorflow/tensorflow/lite/micro/kernels/log_softmax.su ./tensorflow/tensorflow/lite/micro/kernels/logical.d ./tensorflow/tensorflow/lite/micro/kernels/logical.o ./tensorflow/tensorflow/lite/micro/kernels/logical.su ./tensorflow/tensorflow/lite/micro/kernels/logical_common.d ./tensorflow/tensorflow/lite/micro/kernels/logical_common.o ./tensorflow/tensorflow/lite/micro/kernels/logical_common.su ./tensorflow/tensorflow/lite/micro/kernels/logistic.d ./tensorflow/tensorflow/lite/micro/kernels/logistic.o ./tensorflow/tensorflow/lite/micro/kernels/logistic.su ./tensorflow/tensorflow/lite/micro/kernels/logistic_common.d ./tensorflow/tensorflow/lite/micro/kernels/logistic_common.o ./tensorflow/tensorflow/lite/micro/kernels/logistic_common.su ./tensorflow/tensorflow/lite/micro/kernels/lstm_eval.d ./tensorflow/tensorflow/lite/micro/kernels/lstm_eval.o ./tensorflow/tensorflow/lite/micro/kernels/lstm_eval.su ./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.d ./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.o ./tensorflow/tensorflow/lite/micro/kernels/maximum_minimum.su ./tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./tensorflow/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./tensorflow/tensorflow/lite/micro/kernels/mirror_pad.d ./tensorflow/tensorflow/lite/micro/kernels/mirror_pad.o ./tensorflow/tensorflow/lite/micro/kernels/mirror_pad.su ./tensorflow/tensorflow/lite/micro/kernels/mul.d ./tensorflow/tensorflow/lite/micro/kernels/mul.o ./tensorflow/tensorflow/lite/micro/kernels/mul.su ./tensorflow/tensorflow/lite/micro/kernels/mul_common.d ./tensorflow/tensorflow/lite/micro/kernels/mul_common.o ./tensorflow/tensorflow/lite/micro/kernels/mul_common.su ./tensorflow/tensorflow/lite/micro/kernels/neg.d ./tensorflow/tensorflow/lite/micro/kernels/neg.o ./tensorflow/tensorflow/lite/micro/kernels/neg.su ./tensorflow/tensorflow/lite/micro/kernels/pack.d ./tensorflow/tensorflow/lite/micro/kernels/pack.o ./tensorflow/tensorflow/lite/micro/kernels/pack.su ./tensorflow/tensorflow/lite/micro/kernels/pad.d ./tensorflow/tensorflow/lite/micro/kernels/pad.o ./tensorflow/tensorflow/lite/micro/kernels/pad.su ./tensorflow/tensorflow/lite/micro/kernels/pooling.d ./tensorflow/tensorflow/lite/micro/kernels/pooling.o ./tensorflow/tensorflow/lite/micro/kernels/pooling.su ./tensorflow/tensorflow/lite/micro/kernels/pooling_common.d ./tensorflow/tensorflow/lite/micro/kernels/pooling_common.o ./tensorflow/tensorflow/lite/micro/kernels/pooling_common.su ./tensorflow/tensorflow/lite/micro/kernels/prelu.d ./tensorflow/tensorflow/lite/micro/kernels/prelu.o ./tensorflow/tensorflow/lite/micro/kernels/prelu.su ./tensorflow/tensorflow/lite/micro/kernels/prelu_common.d ./tensorflow/tensorflow/lite/micro/kernels/prelu_common.o ./tensorflow/tensorflow/lite/micro/kernels/prelu_common.su ./tensorflow/tensorflow/lite/micro/kernels/quantize.d ./tensorflow/tensorflow/lite/micro/kernels/quantize.o ./tensorflow/tensorflow/lite/micro/kernels/quantize.su ./tensorflow/tensorflow/lite/micro/kernels/quantize_common.d ./tensorflow/tensorflow/lite/micro/kernels/quantize_common.o ./tensorflow/tensorflow/lite/micro/kernels/quantize_common.su ./tensorflow/tensorflow/lite/micro/kernels/read_variable.d ./tensorflow/tensorflow/lite/micro/kernels/read_variable.o ./tensorflow/tensorflow/lite/micro/kernels/read_variable.su
	-$(RM) ./tensorflow/tensorflow/lite/micro/kernels/reduce.d ./tensorflow/tensorflow/lite/micro/kernels/reduce.o ./tensorflow/tensorflow/lite/micro/kernels/reduce.su ./tensorflow/tensorflow/lite/micro/kernels/reduce_common.d ./tensorflow/tensorflow/lite/micro/kernels/reduce_common.o ./tensorflow/tensorflow/lite/micro/kernels/reduce_common.su ./tensorflow/tensorflow/lite/micro/kernels/reshape.d ./tensorflow/tensorflow/lite/micro/kernels/reshape.o ./tensorflow/tensorflow/lite/micro/kernels/reshape.su ./tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.d ./tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.o ./tensorflow/tensorflow/lite/micro/kernels/resize_bilinear.su ./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./tensorflow/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./tensorflow/tensorflow/lite/micro/kernels/round.d ./tensorflow/tensorflow/lite/micro/kernels/round.o ./tensorflow/tensorflow/lite/micro/kernels/round.su ./tensorflow/tensorflow/lite/micro/kernels/select.d ./tensorflow/tensorflow/lite/micro/kernels/select.o ./tensorflow/tensorflow/lite/micro/kernels/select.su ./tensorflow/tensorflow/lite/micro/kernels/shape.d ./tensorflow/tensorflow/lite/micro/kernels/shape.o ./tensorflow/tensorflow/lite/micro/kernels/shape.su ./tensorflow/tensorflow/lite/micro/kernels/slice.d ./tensorflow/tensorflow/lite/micro/kernels/slice.o ./tensorflow/tensorflow/lite/micro/kernels/slice.su ./tensorflow/tensorflow/lite/micro/kernels/softmax.d ./tensorflow/tensorflow/lite/micro/kernels/softmax.o ./tensorflow/tensorflow/lite/micro/kernels/softmax.su ./tensorflow/tensorflow/lite/micro/kernels/softmax_common.d ./tensorflow/tensorflow/lite/micro/kernels/softmax_common.o ./tensorflow/tensorflow/lite/micro/kernels/softmax_common.su ./tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./tensorflow/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./tensorflow/tensorflow/lite/micro/kernels/space_to_depth.d ./tensorflow/tensorflow/lite/micro/kernels/space_to_depth.o ./tensorflow/tensorflow/lite/micro/kernels/space_to_depth.su ./tensorflow/tensorflow/lite/micro/kernels/split.d ./tensorflow/tensorflow/lite/micro/kernels/split.o ./tensorflow/tensorflow/lite/micro/kernels/split.su ./tensorflow/tensorflow/lite/micro/kernels/split_v.d ./tensorflow/tensorflow/lite/micro/kernels/split_v.o ./tensorflow/tensorflow/lite/micro/kernels/split_v.su ./tensorflow/tensorflow/lite/micro/kernels/squared_difference.d ./tensorflow/tensorflow/lite/micro/kernels/squared_difference.o ./tensorflow/tensorflow/lite/micro/kernels/squared_difference.su ./tensorflow/tensorflow/lite/micro/kernels/squeeze.d ./tensorflow/tensorflow/lite/micro/kernels/squeeze.o ./tensorflow/tensorflow/lite/micro/kernels/squeeze.su ./tensorflow/tensorflow/lite/micro/kernels/strided_slice.d ./tensorflow/tensorflow/lite/micro/kernels/strided_slice.o ./tensorflow/tensorflow/lite/micro/kernels/strided_slice.su ./tensorflow/tensorflow/lite/micro/kernels/sub.d ./tensorflow/tensorflow/lite/micro/kernels/sub.o ./tensorflow/tensorflow/lite/micro/kernels/sub.su ./tensorflow/tensorflow/lite/micro/kernels/sub_common.d ./tensorflow/tensorflow/lite/micro/kernels/sub_common.o ./tensorflow/tensorflow/lite/micro/kernels/sub_common.su ./tensorflow/tensorflow/lite/micro/kernels/svdf.d ./tensorflow/tensorflow/lite/micro/kernels/svdf.o ./tensorflow/tensorflow/lite/micro/kernels/svdf.su ./tensorflow/tensorflow/lite/micro/kernels/svdf_common.d ./tensorflow/tensorflow/lite/micro/kernels/svdf_common.o ./tensorflow/tensorflow/lite/micro/kernels/svdf_common.su ./tensorflow/tensorflow/lite/micro/kernels/tanh.d ./tensorflow/tensorflow/lite/micro/kernels/tanh.o ./tensorflow/tensorflow/lite/micro/kernels/tanh.su ./tensorflow/tensorflow/lite/micro/kernels/transpose.d ./tensorflow/tensorflow/lite/micro/kernels/transpose.o ./tensorflow/tensorflow/lite/micro/kernels/transpose.su ./tensorflow/tensorflow/lite/micro/kernels/transpose_conv.d ./tensorflow/tensorflow/lite/micro/kernels/transpose_conv.o ./tensorflow/tensorflow/lite/micro/kernels/transpose_conv.su ./tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./tensorflow/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./tensorflow/tensorflow/lite/micro/kernels/unpack.d ./tensorflow/tensorflow/lite/micro/kernels/unpack.o ./tensorflow/tensorflow/lite/micro/kernels/unpack.su ./tensorflow/tensorflow/lite/micro/kernels/var_handle.d ./tensorflow/tensorflow/lite/micro/kernels/var_handle.o ./tensorflow/tensorflow/lite/micro/kernels/var_handle.su ./tensorflow/tensorflow/lite/micro/kernels/while.d ./tensorflow/tensorflow/lite/micro/kernels/while.o ./tensorflow/tensorflow/lite/micro/kernels/while.su ./tensorflow/tensorflow/lite/micro/kernels/zeros_like.d ./tensorflow/tensorflow/lite/micro/kernels/zeros_like.o ./tensorflow/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-tensorflow-2f-tensorflow-2f-lite-2f-micro-2f-kernels

